services:
  api:
    container_name: nest-js-app
    build:
      context: ./apps/api
      dockerfile: ./Dockerfile.dev
    image: nest-api
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/lms
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - nestjs-network
    depends_on:
      - mongodb
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    restart: unless-stopped

  web:
    container_name: next-js-app
    build:
      context: ./apps/web
      dockerfile: ./Dockerfile.dev
    image: next-web
    ports:
      - "3000:3000"
    networks:
      - nextjs-network
    depends_on:
      - api
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nestjs-network
    restart: always

networks:
  nestjs-network:
    driver: bridge
  nextjs-network:
    driver: bridge